server.port=8080
spring.application.name=spring-boot-benchmark
spring.main.banner-mode=console
logging.level.org.springframework=INFO
spring.devtools.restart.enabled=true

# Actuator Configuration
management.endpoint.health.show-details=ALWAYS
management.endpoint.health.show-components=ALWAYS
management.endpoints.web.exposure.include=*
management.endpoint.health.probes.enabled=true

# JMH configuration
jmh.include=.*Benchmark.*